name: Build Wheels

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      skip_tests:
        description: "Skip cibuildwheel tests"
        required: true
        type: boolean
      os_type:
        description: "OS"
        default: "all"
        type: choice
        options:
        - macos-latest
        - ubuntu-latest
        - windows-latest
        - all


jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}_${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-latest
            arch: auto
          - os: ubuntu-latest
            arch: aarch64
          - os: ubuntu-latest
            arch: i686
          - os: ubuntu-latest
            arch: x86_64
          - os: windows-latest
            arch: AMD64

    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        if: matrix.os == 'ubuntu-latest'
        uses: docker/setup-qemu-action@v2

      - name: Set cibuildwheel env
        id: cibuildwheel_env
        run: |
          CIBW_TEST_SKIP="cp37-*"
          SKIP_CIBW="false"
          if [ "${{ github.event.name }}" == "workflow_dispatch" ]; then
            echo "event is workflow_dispatch"
            if [ "${{ inputs.skip_tests }}" == "true" ]; then
              echo "skip_tests is true"
              CIBW_TEST_SKIP="*"
            fi
            if [ "${{ inputs.os_type }}" != "all" ]; then
              echo "os_type != all"
              if [ "${{ inputs.os_type}}" != "${{ matrix.os }}" ]; then
                echo "os_type == matrix.os"
                SKIP_CIBW="true"
              fi
            fi
          fi
          echo "test_skip=$CIBW_TEST_SKIP" >> $GITHUB_OUTPUT
          echo "skip_build=$SKIP_CIBW" >> $GITHUB_OUTPUT
        shell: bash

      - name: Debug env step
        run: |
          echo "test_skip = ${{ steps.cibuildwheel_env.outputs.test_skip }}"
          echo "skip_build = ${{ steps.cibuildwheel_env.outputs.skip_build }}"
        shell: bash

      - name: Build wheels
        id: build_wheel
        uses: pypa/cibuildwheel@v2.11.2
        env:
          CIBW_ARCHS: ${{ matrix.arch }}
          CIBW_TEST_SKIP: ${{ steps.cibuildwheel_env.outputs.test_skip }}
        if: ${{ steps.cibuildwheel_env.outputs.skip_build }} != "true"
        #    ...
        # with:
        #   package-dir: .
        #   output-dir: wheelhouse
        #   config-file: "{package}/pyproject.toml"

      - uses: actions/upload-artifact@v3
        if: ${{ steps.build_wheel.outcome }} == "success"
        with:
          path: ./wheelhouse/*.whl
